common:
  img_topic: "/usb_cam/image_raw"
  lid_topic: "/livox/lidar"
  imu_topic: "/livox/imu"
  img_en: 0 
  lidar_en: 1
  ros_driver_bug_fix: false     # default = false
  #point_filter_num: 15          # this doesn't exist yet. I want to implement tho.

extrin_calib:
  # (0.0137) (0.0421) (−0.0332)
  extrinsic_T: [ -0.0137, -0.0421, -0.0332 ]  # coordinate system X=-13.7mm, Y=-42.1 Z=33.2   
  extrinsic_R: [ 1, 0, 0, 0, 1, 0, 0, 0, 1]
  Rcl: [1.2184647302603444e-05,-0.9999939076577904,-0.0034906301489807763,0.003490630148980776,0.003490651415223732,-0.9999878153526974,0.9999939076577904,0.0,0.0034906514152237317]
  Pcl: [-0.0001,0.075,-0.08]

time_offset: 
  imu_time_offset: 0
  img_time_offset: -0.14         #-0.2        # default = 0.1 | good = -0.16
  exposure_time_init: 0.00       # default = 0.0

preprocess:
  point_filter_num: 1       # default = 1           || set to 1 for final output and be patient
  filter_size_surf: 0.2   # default = 0.1 | good = 0.1
  lidar_type: 1 # Livox Avia LiDAR
  scan_line: 6
  blind: 1.2       # default = 0.80

vio:
  # Green Points: Successfully tracked inliers.
  # Blue Points: Tracked outliers with higher errors.
  max_iterations: 5                   # default = 5            || increase when creating final output
  outlier_threshold: 100              # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 80                   # default = 100 # no change with 10 ?  
  patch_size: 8                       # default = 8 | good = 0.1
  patch_pyrimid_level: 4              # default = 4 | good = 4  | still good = 16
  normal_en: true                     # default = true
  raycast_en: true                    # default = false
  inverse_composition_en: false       # default = false | no idea if this helps or hinders
  exposure_estimate_en: false          # default = true | good = false
  inv_expo_cov: 0.01                  # default = 0.1

imu:
  imu_en: true #true
  imu_int_frame: 30 #30
  acc_cov: 0.2          # default = 0.5 good=0.25?
  gyr_cov: 0.2          # default = 0.3 good=0.01
  b_acc_cov: 0.01 #0.0001 # 0.1 good = 0.000001?  
  b_gyr_cov: 0.01 #0.0001 # 0.1 good = 0.000001?

lio:
  max_iterations: 5           # default = 5          || increase when creating final output
  dept_err: 0.0               # default = 0.02     | good = 0.002 | better = 0
  beam_err: 0.0               # default = 0.05     | good = 0.005 | better = 0
  min_eigen_value: 0.0025     # 0.005     #default = 0.0025 good=0.002
  voxel_size: 0.5             # default = 0.5   | good = 0.025  ###MOST CRITICAL VALUE IMO###
  max_layer: 2                # deafult = 2    | good = 2
  max_points_num: 100   # default = 50      | good = 25 but maybe only in a small scene
  layer_init_num: [6, 6, 6, 6, 6, 6]         # default = [5, 5, 5, 5, 5]

local_map:  
  map_sliding_en: false # default = false
  half_map_size: 100    # default = 100
  sliding_thresh: 8     # default = 8

uav:
  imu_rate_odom: false
  gravity_align_en: true

publish:
  dense_map_en: true
  pub_effect_point_en: true 
  pub_plane_en: true
  pub_scan_num: 1
  blind_rgb_points: 1.2       # default = 0.0 # good might need to match the lidar blind or more? 

evo:
  seq_name: "RSS"
  pose_output_en: true

pcd_save:
  pcd_save_en: false
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
